/*
A comprehension is a construct of form...

for ( enumerations ) yield e

where enumerations are a list of either generators
and/or filters...

... and e is the body which is evaluated for each
binding generated by the enumerations.

You _can_ omit yield in a comprehension, in which
case the body is being executed for side-effects only.
*/
